# Configuración de cargo-clippy para Xylux IDE
# Versión: 1.1
# Fecha: 2025-08-12
# Mantiene configuraciones solicitadas para pruebas y añade lints para calidad y rendimiento

# Permitir construcciones en pruebas para evitar problemas futuros
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true

## Nota: clippy.toml no soporta listas de deny/warn por nombre de lint.
## Usamos niveles desde Cargo.toml y banderas en CI. Aquí dejamos solo opciones válidas.

# Reglas específicas
msrv = "1.80.0"             # Versión mínima de Rust, alineada con el README