# Configuración de cargo-deny para Xylux IDE
# Asegura que las dependencias sean mínimas y compatibles con la licencia propia de Xylux
# Versión: 0.0.1
# Fecha: 2025-08-12

[graph]
# Desactiva all-features para evitar incluir dependencias innecesarias
all-features = false

# Licencias permitidas y restricciones
[licenses]
# Permite licencias permisivas comunes usadas por ecosistema Rust
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
]
deny = ["GPL-2.0", "GPL-3.0", "AGPL-3.0", "LGPL-2.1", "LGPL-3.0"]
unlicensed = "deny"
copyleft = "deny"

# Verificación de vulnerabilidades
[advisories]
# Deniega cualquier dependencia con vulnerabilidades conocidas
vulnerability = "deny"
# Ignora vulnerabilidades solo si se revisan manualmente (lista vacía por ahora)
ignore = []

# Verificación de bans
[bans]
# Deniega múltiples versiones de la misma dependencia para evitar conflictos
multiple-versions = "deny"
# Evita dependencias con comodines para mayor control
wildcards = "deny"

# Fuentes permitidas
[sources]
# Solo permite crates de crates.io
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]