# Configuración de cargo-deny para Xylux IDE
# Asegura que las dependencias sean mínimas y compatibles con la licencia propia de Xylux
# Versión: 0.0.1
# Fecha: 2025-08-12

[graph]
# Desactiva all-features para evitar incluir dependencias innecesarias
all-features = false

# Licencias permitidas y restricciones
[licenses]
# No se permiten licencias abiertas por defecto; solo dependencias específicas aprobadas
allow = []
# Deniega explícitamente licencias no compatibles con el enfoque propietario
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-2.1",
    "LGPL-3.0",
]
# Configura para revisar caso por caso las licencias de dependencias
unlicensed = "deny"
copyleft = "deny"
# Lista de dependencias con licencias permitidas específicamente
allow-osi-fsf-free = "neither"
[licenses.allowed]
unicode-width = ["MIT", "Apache-2.0"]
libc = ["MIT", "Apache-2.0"]
winapi = ["MIT", "Apache-2.0"]
tempfile = ["MIT", "Apache-2.0"]

# Verificación de vulnerabilidades
[advisories]
# Deniega cualquier dependencia con vulnerabilidades conocidas
vulnerability = "deny"
# Ignora vulnerabilidades solo si se revisan manualmente (lista vacía por ahora)
ignore = []

# Verificación de bans
[bans]
# Deniega múltiples versiones de la misma dependencia para evitar conflictos
multiple-versions = "deny"
# Deniega dependencias no aprobadas explícitamente
deny = []
# Solo permite dependencias esenciales para Xylux IDE
allow = [
    "unicode-width",
    "libc",
    "winapi",
    "tempfile",
]
# Evita dependencias con comodines para mayor control
wildcards = "deny"

# Fuentes permitidas
[sources]
# Solo permite crates de crates.io
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]